server:
  port: ${port:8080}

logging:
  level:
    priv:
      noby:
        easycode: debug

mybatis:
  type-aliases-package: priv.noby.easycode.entity
  mapper-locations: classpath:/mapper/*Dao.xml

spring:
  application:
    name: easycode
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stage4?serverTimezone=UTC
    username: root
    password: 123
    druid:
      max-active: 50
      initial-size: 10
      min-idle: 10
      max-wait: 100000


