###
GET http://localhost:8080/emp/37
Content-Type: application/json

###
POST http://localhost:8080/emp
Content-Type: application/json

{
  "ename": "njb",
  "eid": 34,
  "did": 1002,
  "hiredate": "2020-1-1"
}