server:
  port: ${port:3031}
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors: #跨域
        add-to-simple-url-handler-mapping: true   #针对OPTION跨域运行
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders: "*"               #允许请求头
      routes: #路由配置
        - id: provider-emp                #路由id,自定义路由名
          #          uri: http://localhost:8081          #映射路径
          uri: lb://provider-emp          #支持使用服务名调用(来自Eureka)，支持负载均衡
          predicates: #断言，条件判断
            - Path=/emp/**
            #            - After=2022-08-10T10:03:02.306+08:00[Asia/Shanghai]
            #            - Cookie=c, ch.p
#            - Header=h1, \d+
          filters:
            - AddRequestHeader=h2, blue       #请求经过网关，网关会在请求中添加请求头，
            - AddResponseHeader=test, mytest   #请求经过网关，网关会在请求中添加响应头，
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6061/eureka