server:
  port: 8080
spring:
  rabbitmq:
    host: 192.168.122.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated    #生产者开启confirm确认
    publisher-returns: true               #生产者开启return确认
    listener:
      simple:
        acknowledge-mode: manual    #消费者开启手动消息确认
        prefetch: 1                #限流，一个队列中正在处理的消息消费之后才会让下一个消息处于待处理状态（不限流的情况下所有的消息都是待处理状态）


