server:
  port: ${port:7071}

logging:
  level:
    priv.noby.consumer.emp: debug
spring:
  application:
    name: consumer-emp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/note?serverTimezone=UTC
    username: root
    password: 123
#  cloud:
#    alibaba:
#      seata:
#        tx-service-group: fsp_tx_group
mybatis:
  type-aliases-package: priv.noby.common.entity
  mapper-locations: classpath:/mapper/*Dao.xml
#eureka:
#  client:
#    fetch-registry: true            #微服务可以调用其它服务
#    register-with-eureka: true      #微服务可以供其它服务调用
#    service-url:
#      defaultZone: http://localhost:6061/eureka
feign:
  client:
    config:
      default:      #配置不同微服务支持的超时时间，default就是默认所有的微服务使用相同的超时时间
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full    #OpenFeing日志，当spring的日志打开该日志才生效 NONE，BASIC，HEADERS，FULL





