logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    priv.noby: debug
spring:
  rabbitmq:
    host: 192.168.122.128 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated #开启publisher-confirm，这里支持两种类型：同步等待confirm结果，直到超时。异步回调，定义ConfirmCallback，MQ返回结果时会回调这个ConfirmCallback
    publisher-returns: true #开启publish-return功能，定义ReturnCallback回调函数
    template:
      mandatory: true #定义消息路由失败时的策略。true，则调用ReturnCallback；false：则直接丢弃消息