server:
  port: ${port:8081}
logging:
  level:
    priv.noby.provider.emp: debug
spring:
  application:
    name: provider-emp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/note?serverTimezone=UTC
    username: root
    password: 123
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
mybatis:
  type-aliases-package: priv.noby.common.entity
  mapper-locations: classpath:/mapper/*Dao.xml
eureka:
  client:
    fetch-registry: true            #微服务可以调用其它服务
    register-with-eureka: true      #微服务可以供其它服务调用
    service-url:
      defaultZone: http://localhost:6061/eureka
  instance:
    lease-renewal-interval-in-seconds: 30      #默认客户端每隔30s发送一个心跳包到服务器
    lease-expiration-duration-in-seconds: 90   #持续90s没有发送心跳包，服务端剔除服务


