logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    priv.noby: debug
spring:
  rabbitmq:
    host: localhost # rabbitMQ的ip地址
    port: 5672 # 端口
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        prefetch: 1
        # 配置该消费者的消费模式，包括手动ack、自动ack、关闭ack
        # manual：手动ack，需要在业务代码结束后，调用api发送ack。
        # auto(默认)：自动ack，由spring监测listener代码是否出现异常，没有异常则返回ack；抛出异常则返回nack(当收到ack时mq会将消息删除，当收到nack时mq会将消息保留)
        # none：关闭ack，MQ假定消费者获取消息后会成功处理，因此消息投递后立即被删除
        acknowledge-mode: auto
        # 消息重试机制，开启后消费者失败后会在本地重试，当重试次数完了之后还是失败会根据配置中的MessageRecoverer规则处理消息发往哪个队列（默认为舍弃消息），同时向mq发送Reject，mq收到会删除消息
        retry:
          enabled: true # 开启消费者失败重试（默认为false）
          initial-interval: 1000 # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false(每次尝试的状态是否累加)

