### 调用本模块controller查询emp
GET http://localhost:8081/emp/1


### 调用本模块controller添加emp
POST http://localhost:8081/emp
Content-Type: application/json

{
  "ename": "noby",
  "did": 2,
  "hiredate": "2021-10-12"
}