server:
  port: ${port:8081}
logging:
  level:
    priv.noby.provider.emp: debug
spring:
  application:
    name: provider-emp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/note?serverTimezone=UTC
    username: root
    password: 123

mybatis:
  type-aliases-package: priv.noby.common.entity
  mapper-locations: classpath:/mapper/*Dao.xml


