server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stage4?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    priv.noby: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: priv.noby.elasticsearch.pojo